import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :eden, EdenWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# TLS is terminated at the reverse proxy (Caddy — see deploy/), which owns the
# http→https redirect (domain phase) + HSTS. The app runs plain HTTP internally,
# so there is deliberately NO compile-time `force_ssl` here: it would 301 every
# page during the initial bare-IP/HTTP phase (#85). `Plug.RewriteOn` in the
# endpoint trusts Caddy's `X-Forwarded-Proto`, so the connection scheme (and thus
# the Secure cookie flag) is correct in the HTTPS phase.

# Do not print debug messages in production
config :logger, level: :info

# Structured JSON logs in production (ready for aggregation/search). Dev and
# test keep the human-readable formatter from config/config.exs. This configures
# the default handler's formatter (a {module, opts} tuple) — note `:default_formatter`
# expects formatter *options*, not a module, so the module goes via `:default_handler`.
config :logger, :default_handler,
  formatter: {LoggerJSON.Formatters.Basic, metadata: [:request_id]}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
