defmodule EdenWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :eden

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # max_age matches the server-side session-token validity (UserToken
  # @session_validity_in_days, 60 days): without it the cookie is browser-
  # session-scoped, and the mobile WebViews (#417 — Android CookieManager on
  # process kill) drop it between app launches, logging the person out on every
  # restart. A persistent cookie is messenger parity (Telegram/WhatsApp Web);
  # revocation stays fully server-side — "log out everywhere", password change,
  # deactivation and admin resets kill the TOKEN, so a lingering cookie is inert.
  @session_options [
    store: :cookie,
    key: "_eden_key",
    signing_salt: "WX07GeEl",
    same_site: "Lax",
    max_age: 60 * 24 * 60 * 60
  ]

  # max_frame_size must fit a whole upload chunk in ONE WebSocket frame — LiveView pushes each chunk as
  # a binary frame, so the cap must exceed the chunk + protocol overhead, else a bumped chunk_size would
  # trip Bandit's :max_frame_size_exceeded. DERIVED from the chunk (Eden.Chat.upload_max_frame_size/0 =
  # 4× the chunk) so the two can't drift out of sync (#327 review). LiveView's own diff/event frames are
  # tiny; longpoll carries chunks in the POST body (not frame-capped), so it needs nothing here.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      connect_info: [session: @session_options],
      max_frame_size: Eden.Chat.upload_max_frame_size()
    ],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :eden,
    gzip: not code_reloading?,
    only: EdenWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :eden
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  # Behind the prod reverse proxy (Caddy terminates TLS), trust its forwarded
  # headers so `conn.scheme` reflects the public scheme — this drives the session
  # cookie's Secure flag in the HTTPS phase — and `conn.remote_ip` reflects the
  # real client, which the #236 per-IP throttle keys on. Safe: the app port is
  # never exposed directly (only Caddy reaches it), Caddy overwrites x-forwarded-for
  # with the true peer (see deploy/Caddyfile, so a client can't spoof it), and in
  # dev/test no proxy sets these headers.
  plug Plug.RewriteOn,
       [:x_forwarded_for, :x_forwarded_proto, :x_forwarded_host, :x_forwarded_port]

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Liveness probe for the container / reverse-proxy. Answered here — before
  # parsing, session, and the router — so it stays cheap and still responds even
  # if routing or the database is degraded.
  plug :health_check

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EdenWeb.Router

  def health_check(%Plug.Conn{request_path: path} = conn, _opts)
      when path in ["/healthz", "/healthz/"] do
    conn
    |> Plug.Conn.put_resp_content_type("text/plain")
    |> Plug.Conn.send_resp(200, "ok")
    |> Plug.Conn.halt()
  end

  def health_check(conn, _opts), do: conn
end
