const path = require("path"); const home = require("os").homedir()
const { firefox } = require(path.join(home, "node_modules/@playwright/test"))
const e2e = path.join(__dirname, "..")
const seed = require(path.join(e2e, ".seed.json"))
;(async () => {
  const b = await firefox.launch()
  const ctx = await b.newContext({ storageState: path.join(e2e, ".auth", "alice.json") })
  const p = await ctx.newPage()
  await p.setViewportSize({ width: 900, height: 780 })
  await p.goto(seed.base_url + "/app/c/" + seed.dm_id)
  await p.waitForFunction(() => window.liveSocket?.isConnected())
  const txt = "Меняю это сообщение " + Date.now()
  await p.fill("#composer-body", txt); await p.locator("#composer").evaluate(f=>f.requestSubmit())
  const bubble = p.locator(".ed-bubble", { hasText: txt }).first()
  await bubble.waitFor()
  // retry the contextmenu until the menu is visible (mirrors the harness openMenu)
  const menu = p.locator(".ed-menu:visible").first()
  for (let i=0;i<10;i++){ await bubble.dispatchEvent("contextmenu",{bubbles:true}); if(await menu.isVisible().catch(()=>false)) break; await p.waitForTimeout(300) }
  await menu.locator(".ed-menu__item",{hasText:"Edit"}).click()
  await p.waitForSelector(".ed-reply-bar--edit")
  await p.fill("#composer-body", txt + " — поправлено")
  await p.waitForTimeout(250)
  await p.screenshot({ path: "test/e2e/scratch/edit-mode.png", clip: { x: 0, y: 440, width: 900, height: 340 } })
  // now save + screenshot the edited message with the marker
  await p.locator("#composer").evaluate(f=>f.requestSubmit())
  await p.locator(".ed-edited").first().waitFor()
  await p.waitForTimeout(300)
  await p.screenshot({ path: "test/e2e/scratch/edited-msg.png", clip: { x: 0, y: 300, width: 900, height: 300 } })
  await b.close()
})().catch(e=>{console.error(e.message);process.exit(1)})
