const path = require("path"); const home = require("os").homedir()
const { firefox } = require(path.join(home, "node_modules/@playwright/test"))
;(async () => {
  const b = await firefox.launch(); const p = await b.newPage()
  await p.setViewportSize({ width: 720, height: 760 })
  await p.goto("http://localhost:4001/login")
  await p.waitForLoadState("networkidle")
  const title = await p.title()
  const icon = await p.evaluate(() => document.querySelector("link[rel~='icon']")?.href)
  console.log("document.title =", JSON.stringify(title))
  console.log("favicon href    =", icon)
  await p.screenshot({ path: "test/e2e/scratch/login-rebrand.png" })
  await b.close()
})().catch(e => { console.error(e.message); process.exit(1) })
