const path = require("path"); const home = require("os").homedir()
const { firefox } = require(path.join(home, "node_modules/@playwright/test"))
const e2e = path.join(__dirname, "..")
const seed = require(path.join(e2e, ".seed.json"))
;(async () => {
  const b = await firefox.launch()
  const ctx = await b.newContext({ storageState: path.join(e2e, ".auth", "alice.json") })
  const p = await ctx.newPage()
  await p.setViewportSize({ width: 1320, height: 900 })
  await p.goto(seed.base_url + "/app/c/" + seed.group_id)
  await p.waitForFunction(() => window.liveSocket?.isConnected())
  await p.locator("[data-profile-trigger]").click()
  await p.waitForSelector(".ed-profile")
  await p.waitForTimeout(300)
  await p.locator(".ed-profile").screenshot({ path: "test/e2e/scratch/panel-group.png" })
  await b.close()
})().catch(e => { console.error(e.message); process.exit(1) })
