// Which pixels the browser actually downloads for a photo tile (#516, part of epic #506).
//
// One 800px preview served every surface in the app: an album tile three-across is ~105 CSS px,
// the gallery grid ~127, the lightbox reel 44. The fix gives each `<img>` two candidates and an
// accurate `sizes`, and lets the browser choose.
//
// The oracle is `currentSrc` — the URL the browser RESOLVED, after applying `sizes` and the
// device pixel ratio. Asserting on the `srcset` attribute would only prove the markup exists;
// this proves the choice landed, which is the part that can silently be wrong (a `sizes` that
// overstates the box sends the browser back to the 800px candidate and saves nothing).
const { test, expect } = require("../helpers/fixtures")
const path = require("path")
const fix = (n) => path.join(__dirname, "..", "fixtures", n)

test.describe.configure({ mode: "serial" })

test("an album tile downloads the tile-sized variant, not the 800px preview", async ({
  alice,
  seed,
}, testInfo) => {
  test.setTimeout(120_000)

  await alice.goto(`/app/c/${seed.dm_id}`)
  await alice.waitForFunction(() => window.liveSocket?.isConnected())
  // A connected socket is not a ready composer: `setInputFiles` fired immediately after connect
  // stages nothing, because the LiveView upload channel is not listening yet. Every upload spec
  // in this suite has this shape and they fail on `main` for it — unrelated to what is being
  // measured here, so wait for the pane instead of racing it.
  await alice.locator(`#message-scroll[data-conversation-id="${seed.dm_id}"]`).waitFor()
  await alice.waitForTimeout(1000)

  // Three photos, so the mosaic lays them out three-across — the case where the 800px preview is
  // most wasteful and where `sizes` has to be right for the browser to say so.
  await alice
    .locator('#composer input[name="attachment"]')
    .setInputFiles([fix("sample1.png"), fix("sample2.png"), fix("sample3.png")])
  await expect(alice.locator("[data-upload-preview]")).toBeVisible()
  await alice.locator("#compose-caption").fill("variants")
  await alice.locator("#compose-caption").press("Enter")

  const tiles = alice.locator(".ed-album__tile img")
  await expect(tiles.first()).toBeVisible({ timeout: 20_000 })

  // The preview is generated by a worker, so the srcset appears on a later render. Wait for the
  // attribute rather than a fixed sleep: without a preview there is deliberately no srcset at all.
  await expect
    .poll(
      async () => await tiles.first().evaluate((i) => i.getAttribute("srcset") || ""),
      { timeout: 30_000, message: "the album tile never got a srcset" },
    )
    .toContain("/thumb/s")

  // Only tiles that HAVE a variant to choose from. This conversation accumulates albums across
  // runs, and older photos whose preview never got generated correctly carry no srcset at all —
  // including them would measure the fixture's history instead of this change.
  const chosen = await tiles.evaluateAll((imgs) =>
    imgs
      .filter((i) => (i.getAttribute("srcset") || "").includes("/thumb/s"))
      .map((i) => ({
        current: i.currentSrc,
        sizes: i.getAttribute("sizes"),
        box: Math.round(i.getBoundingClientRect().width),
        dpr: window.devicePixelRatio,
      })),
  )

  expect(chosen.length, "no tile offered a variant — nothing was measured").toBeGreaterThan(0)

  const line = chosen
    .map((c) => `box=${c.box}px sizes=${c.sizes} dpr=${c.dpr} -> ${c.current.split("/").pop()}`)
    .join(" | ")
  console.log(line)
  testInfo.annotations.push({ type: "measurement", description: line })

  for (const c of chosen) {
    // `sizes` must describe the real box. A stale value is the failure mode that leaves the
    // markup looking correct while the browser keeps fetching the big candidate.
    expect(Math.abs(parseInt(c.sizes, 10) - c.box), `sizes=${c.sizes} but the box is ${c.box}px`)
      .toBeLessThanOrEqual(4)

    // 105 CSS px at any DPR up to 2 needs at most 210 device px, so the 256 candidate wins.
    if (c.box * c.dpr <= 256) {
      expect(c.current, `${line} — the browser still chose the 800px preview`).toContain("/thumb/s")
    }
  }
})

test("a sidebar avatar downloads the display-sized variant", async ({ alice, seed }, testInfo) => {
  // The avatar blob is a 512px JPEG and the largest avatar the app renders is 56 CSS px. This
  // asserts the wire, not the file: what the route actually returned for a sidebar circle.
  const responses = []
  alice.on("response", (r) => {
    if (/\/(users|conversations|channels)\/\d+\/avatar/.test(r.url())) responses.push(r)
  })

  await alice.goto("/app")
  await alice.waitForFunction(() => window.liveSocket?.isConnected())
  await alice.waitForTimeout(1500)

  // Only the ones that actually returned an avatar. The seed carries users whose `avatar_key`
  // points at a blob that is not on this machine's disk, and those 404 — before this change as
  // well, so treating them as failures would be measuring the fixture, not the code.
  const served = responses.filter((r) => r.status() === 200)
  test.skip(served.length === 0, "no avatar blob on this stand — nothing to measure")

  for (const r of served) {
    const body = await r.body()
    const type = r.headers()["content-type"] || ""
    const line = `${r.url().split("/").slice(-2).join("/")}: ${body.length} B ${type}`
    console.log(line)
    testInfo.annotations.push({ type: "measurement", description: line })

    expect(type, `${line} — the master JPEG is still being served`).toContain("image/webp")
  }
})
